name: Manually Build
on:
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          export ELECTRON_SKIP_BINARY_DOWNLOAD=1
          npm install
          cd src/webui/FE
          npm install

      - name: Build
        run: |
          npm run build
          npm run build-webui

      - name: Compress dist
        run: |
          mkdir llonebot-win-x64
          sudo apt install zip -y
          cd ./dist/
          mv 使用说明.txt ../llonebot-win-x64/
          zip -r ../LLOneBot.zip ./*

      - name: Compress for Windows
        run: |
          cd llonebot-win-x64
          mv ../dist/更新日志.txt ./
          mv ../dist ./llonebot
          wget https://github.com/linyuchen/PMHQ/releases/latest/download/pmhq-win-x64.zip
          unzip pmhq-win-x64.zip
          rm pmhq-win-x64.zip
          mv pmhq-win-x64.exe llonebot.exe
          wget https://github.com/LLOneBot/exe/releases/latest/download/node.exe -O llonebot/node.exe
          zip -r ../LLOneBot-win-x64.zip ./*
          wget https://github.com/LLOneBot/exe/releases/latest/download/ffmpeg.exe -O llonebot/ffmpeg.exe
          wget https://github.com/LLOneBot/exe/releases/latest/download/ffprobe.exe -O llonebot/ffprobe.exe
          zip -r ../LLOneBot-win-x64-ffmpeg.zip ./*

      - name: Upload LLOneBot.zip
        uses: actions/upload-artifact@v4
        with:
          name: LLOneBot
          path: LLOneBot.zip
          retention-days: 30

      - name: Upload LLOneBot-win-x64.zip
        uses: actions/upload-artifact@v4
        with:
          name: LLOneBot-win-x64
          path: LLOneBot-win-x64.zip
          retention-days: 30

      - name: Upload LLOneBot-win-x64-ffmpeg.zip
        uses: actions/upload-artifact@v4
        with:
          name: LLOneBot-win-x64-ffmpeg
          path: LLOneBot-win-x64-ffmpeg.zip
          retention-days: 30

      - name: Compress for mac-x64
        run: |
          mkdir llonebot-mac-x64
          mkdir llonebot-mac-x64/llonebot
          mkdir llonebot-mac-x64/
          cp -r ./dist/* llonebot-mac-x64/llonebot/
          wget https://github.com/LLOneBot/exe/releases/latest/download/node-darwin-x64 -O llonebot-mac-x64/llonebot/node
          wget https://github.com/linyuchen/PMHQ/releases/latest/download/pmhq-mac-x64.zip
          unzip pmhq-win-x64.zip
          rm pmhq-mac-x64.zip
          mv pmhq llonebot-mac-x64/
          wget https://raw.githubusercontent.com/LLOneBot/LLOneBot/refs/heads/main/script/start-mac.sh -O llonebot-mac-x64/start.sh
          zip -r LLOneBot-mac-x64.zip ./llonebot-mac-x64/*

      - name: Upload LLOneBot-mac-x64.zip
        uses: actions/upload-artifact@v4
        with:
          name: LLOneBot-mac-x64
          path: LLOneBot-mac-x64.zip
          retention-days: 30

      - name: Compress for mac-arm64
        run: |
          mkdir llonebot-mac-arm64
          mkdir llonebot-mac-arm64/llonebot
          mkdir llonebot-mac-arm64/
          cp -r ./dist/* llonebot-mac-arm64/llonebot/
          wget https://github.com/LLOneBot/exe/releases/latest/download/node-darwin-arm64 -O llonebot-mac-arm64/llonebot/node
          wget https://github.com/linyuchen/PMHQ/releases/latest/download/pmhq-mac-arm64.zip
          unzip pmhq-win-arm64.zip
          rm pmhq-mac-arm64.zip
          mv pmhq llonebot-mac-arm64/
          wget https://raw.githubusercontent.com/LLOneBot/LLOneBot/refs/heads/main/script/start-mac.sh -O llonebot-mac-arm64/start.sh
          zip -r LLOneBot-mac-arm64.zip ./llonebot-mac-arm64/*

      - name: Upload LLOneBot-mac-arm64.zip
        uses: actions/upload-artifact@v4
        with:
          name: LLOneBot-mac-arm64
          path: LLOneBot-mac-arm64.zip
          retention-days: 30
